# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import leisure_search.leisure.models


class Migration(migrations.Migration):

    dependencies = [
        ('leisure', '0004_auto_20170602_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=leisure_search.leisure.models.institution_photo_directory_path, verbose_name='Photo'),
        ),
    ]
